### ISSUE TITLE
Create tunnel for container?

### ISSUE THREAD

**Issue by Sir-Will** [jnovack/docker-autossh#19]
Hello,

I'm looking for a way to create a tunnel for a redash container. Is it possible to use this docker container to create an autossh tunnel and allow the redash container to use it?

This is the command I'm currently using which I would like to turn into an autossh container:
`autossh -M 20017 -f -N -L 3304:127.0.0.1:3304 -p 22 -i /tunnel/key ssh-tunnel@000.000.000.000`

**Comment by jnovack** [comment]
Yes, it's possible to use this container for this purpose.

You could also use an [ambassador container](https://github.com/jnovack/docker-ambassador).

**Comment by Sir-Will** [comment]
How would the configuration for that look like?
I added the following to docker-compose but redash doesn't seem to be able to connect:
```yml
autossh:
  image: jnovack/autossh
  environment:
    - SSH_HOSTUSER=ssh-tunnel
    - SSH_HOSTNAME=000.000.000.000
    - SSH_KEY_FILE=/tunnel/key
    - SSH_TUNNEL_REMOTE=*:3304
    - SSH_TUNNEL_HOST=127.0.0.1
    - SSH_TUNNEL_LOCAL=3304
    - SSH_MODE=-L
  restart: always
  volumes:
    - /srv/docker/redash:/tunnel
```

**Comment by jnovack** [comment]
View your `docker logs` for this container, it should be printing out exactly which command it is running for SSH for debugging.

**Comment by Sir-Will** [comment]
I looked at that and it doesn't have the `-i /tunnel/key` in the command.
Can the redash container even access the tunnel because autossh is in its own container?

**Comment by jnovack** [comment]
Lines 4 through 10 of `entrypoint.sh` copy in and load the `SSH_KEY_FILE`.

https://github.com/jnovack/docker-autossh/blob/105f6a749c17dc9767860b3c07b0c7930a8e13b4/entrypoint.sh#L4-L10

**Comment by Sir-Will** [comment]
It doesn't show that error, so I suppose that is working. Is there anything else which needs to be done that the redash container can use the autossh container?
```
mym_new_autossh_1    | Agent pid 8
mym_new_autossh_1    | Identity added: (stdin) ((stdin))
mym_new_autossh_1    | [INFO] Using autossh 1.4g
mym_new_autossh_1    | [INFO] Tunneling ssh-tunnel@000.000.000.000:*:3304 to 127.0.0.1:3304
mym_new_autossh_1    | > autossh -M 0 -N -o StrictHostKeyChecking=no -o ServerAliveInterval=10 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -t -t -L *:3304:127.0.0.1:3304 -p 22 ssh-tunnel@000.000.000.000
mym_new_autossh_1    | Warning: Permanently added '000.000.000.000' (ECDSA) to the list of known hosts.
```
(000.000.000.000 = IP of the server)

**Comment by jnovack** [comment]
This is the command it is running:

```
autossh -M 0 -N -o StrictHostKeyChecking=no -o ServerAliveInterval=10 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -t -t -L *:3304:127.0.0.1:3304 -p 22 ssh-tunnel@000.000.000.000
```

does this command work to satisfy your requirements if it were NOT run in a docker container?

**Comment by Sir-Will** [comment]
Yes, it's working outside a container.

**Comment by jnovack** [comment]
When you run the command on your desktop, `127.0.0.1` is your desktop. When you run the command in a container, `127.0.0.1` is the container.

**Comment by Sir-Will** [comment]
I'm aware, that's why I wonder how I can provide the tunnel to the other container and not only to the autossh container itself.

**Comment by jnovack** [comment]
https://docs.docker.com/engine/reference/builder/#expose

**Comment by Sir-Will** [comment]
This is what I have now but I'm unable to connect to 173.20.5.1:3304
```yml
autossh:
  image: jnovack/autossh
  expose:
    - "3304"
  environment:
    - SSH_HOSTUSER=ssh-tunnel
    - SSH_HOSTNAME=000.000.000.000
    - SSH_KEY_FILE=/tunnel/key
    - SSH_TUNNEL_REMOTE=*:3304
    - SSH_TUNNEL_HOST=127.0.0.1
    - SSH_TUNNEL_LOCAL=3304
    - SSH_MODE=-L
  restart: always
  volumes:
    - /srv/docker/redash:/tunnel
  networks:
    redash_static_network:
      ipv4_address: 173.20.5.1
networks:
redash_static_network:
  ipam:
    config:
      - subnet: 173.20.0.0/16
        #docker-compose v3+ do not use ip_range
        ip_range: 173.28.5.0/24
```
