### ISSUE TITLE
Problems with docker-compose example in the README.md

### ISSUE THREAD

**Issue by qmnonic** [jnovack/docker-autossh#5]
Reading the ssh key file seems to fail as specified in the example, because it refers to the id_rsa file directly.
```    
  volumes:
     - /etc/autossh/id_rsa:/id_rsa
```

It works if you map the volume to the directory containing the id_rsa file, and specify the path via `SSH_KEY_FILE` as an environment variable.
```  
   environment:
     SSH_KEY_FILE: /ssh/id_rsa  
   volumes:
     - /etc/autossh=:/ssh
```

Default SSH_MODE environment variable doesn't work with a for a strict proxy (no login).  Must set it to:
```
SSH_MODE: -Ng -L
```
